export const MAX_AUTOPLAY_COUNT = 20;
export const MAX_AUTOPLAY_INTERVAL_SECONDS = 300;
export const DEFAULT_AUTOPLAY_INTERVAL_SECONDS = 1;
export const CAROUSEL_INTERVAL = 2500;
export const IMAGE_PREFETCH_CONCURRENCY = 3;
